### PR TITLE
remove usage of Newtonsoft.Json

### LINKED ISSUE #2009: GitVersionTask 5.1.3 fails on appveyor FileLoadException
GitVersionTask is unable to load `Newtonsoft.Json`

Unsure what makes it fail on appveyor: https://ci.appveyor.com/project/nmklotas/gitlabapiclient/builds/29753347#L138

works just fine locally and on GitHub Action

### PR DESCRIPTION
**Pull request by casz**
fixes #2009

### CODE REVIEW

File: src/GitVersionCore/BuildServers/AppVeyor.cs [hunk 1]
```diff
@@ -40,13 +35,9 @@ public override string[] GenerateSetParameterMessage(string name, string value)
         {
             var httpClient = GetHttpClient();
 
-            var body = new
-            {
-                name = $"GitVersion_{name}",
-                value = $"{value}"
-            };
+            var body = $"{{\"name\": \"GitVersion_{name}\",\"value\": \"{value}\"}}";
```
Comment (casz) [inline src/GitVersionCore/BuildServers/AppVeyor.cs]: I doubt we need to evaluate whether value is an Integer or not.

**Comment by casz** [comment]
I see the appveyor actually tests the built DLL.

**Comment by casz** [comment]
@asbjornu unsure why docker tests failed.

**Comment by arturcic** [comment]
@casz there are 2 more files to change, Directory.Build.props and test.props in the src folder

**Comment by casz** [comment]
There are some tests that I rather not rewrite I think it's fine that tests use newtonsoft.json 😄

**Comment by casz** [comment]
The problem that newtonsoft.json solves in tests is deserialize json to poco.

**Comment by casz** [comment]
@arturcic I can use system.text.json instead for the tests if you want?

Or I can use `JavaScriptSerializer` to deserialize as it is not performance critical.

**Comment by arturcic** [comment]
Sure works for me

**Comment by casz** [comment]
Hmmm that's odd system.text.json is already included... Looking into which package pulls it in 🤔

**Comment by casz** [comment]
Works for me:
image

**Comment by casz** [comment]
I am not sure how this ever worked, it seemed that Newtonsoft.Json was filtering out none JSON objects from a string object.

I dare not touch...

**Comment by casz** [comment]
I see Newtonsoft.Json by default have no error handling setup.

So even if it receives a message like:

```
INFO [01/07/20 20:31:23:77] Applicable build agent found: 'TeamCity'.INFO [01/07/20 20:31:23:86] Working directory: C:\Users\josep\AppData\Local\Temp\TestRepositories\057e9db6-9c1a-4884-8ceb-89e8cc210785INFO [01/07/20 20:31:23:88] IsDynamicGitRepository: FalseINFO [01/07/20 20:31:23:92] Returning Project Root from DotGitDirectory: C:\Users\josep\AppData\Local\Temp\TestRepositories\057e9db6-9c1a-4884-8ceb-89e8cc210785\.git\ - C:\Users\josep\AppData\Local\Temp\TestRepositories\057e9db6-9c1a-4884-8ceb-89e8cc210785\INFO [01/07/20 20:31:23:92] Running on Windows.INFO [01/07/20 20:31:23:92] Applicable build agent found: 'TeamCity'.WARN [01/07/20 20:31:23:93] TeamCity doesn't make the current branch available through environmental variables.

Depending on your authentication and transport setup of your git VCS root things may work. In that case, ignore this warning.

In your TeamCity build configuration, add a parameter called `env.Git_Branch` with value %teamcity.build.vcs.branch.<vcsid>%

See http://gitversion.readthedocs.org/en/latest/build-server-support/build-server/teamcity for more infoINFO [01/07/20 20:31:23:93] Branch from build environment: INFO [01/07/20 20:31:23:93] Begin: Normalizing git directory for branch ''  INFO [01/07/20 20:31:23:98] One remote found (origin -> 'C:\git\code\GitVersion\src\GitVersionExe.Tests\bin\Debug\net472\TestRepositories\b58f239e-9bb0-41c2-9156-9160b6d64e8e').  INFO [01/07/20 20:31:23:98] Fetching from remote 'origin' using the following refspecs: +refs/pr/*/head:refs/remotes/origin/pr/*, +refs/heads/*:refs/remotes/origin/*.  INFO [01/07/20 20:31:24:01] Creating local branch from remote tracking 'refs/remotes/origin/FeatureBranch'.  INFO [01/07/20 20:31:24:04] End: Normalizing git directory for branch '' (Took: 110.00ms)  ERROR [01/07/20 20:31:24:18] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: ref 'refs/remotes/origin/FeatureBranch' doesn't match the destination
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_refspec_rtransform(IntPtr refSpecPtr, String name)
   at LibGit2Sharp.Remote.FetchSpecTransformToSource(String reference)
   at LibGit2Sharp.BranchUpdater.GetUpstreamInformation(String canonicalName, String& remoteName, String& mergeBranchName)
   at LibGit2Sharp.BranchUpdater.SetUpstream(String upstreamBranchName)
   at GitVersion.Helpers.GitRepositoryHelper.<>c__DisplayClass8_1.<CreateOrUpdateLocalBranchesFromRemoteTrackingOnes>b__1(BranchUpdater b) in C:\git\code\GitVersion\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 298
   at LibGit2Sharp.BranchCollection.Update(Branch branch, Action`1[] actions)
   at GitVersion.Helpers.GitRepositoryHelper.CreateOrUpdateLocalBranchesFromRemoteTrackingOnes(ILog log, Repository repo, String remoteName) in C:\git\code\GitVersion\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 298
   at GitVersion.Helpers.GitRepositoryHelper.NormalizeGitDirectory(ILog log, IEnvironment environment, String gitDirectory, AuthenticationInfo authentication, Boolean noFetch, String currentBranch, Boolean isDynamicRepository) in C:\git\code\GitVersion\src\GitVersionCore\Helpers\GitRepositoryHelper.cs:line 41
   at GitVersion.GitPreparer.NormalizeGitDirectory(AuthenticationInfo auth, String targetBranch, String gitDirectory, Boolean isDynamicRepository) in C:\git\code\GitVersion\src\GitVersionCore\GitPreparer.cs:line 190
   at GitVersion.GitPreparer.Prepare(Boolean normalizeGitDirectory, String currentBranch, Boolean shouldCleanUpRemotes) in C:\git\code\GitVersion\src\GitVersionCore\GitPreparer.cs:line 62
   at GitVersion.GitVersionCalculator.CalculateVersionVariables() in C:\git\code\GitVersion\src\GitVersionCore\GitVersionCalculator.cs:line 52
   at GitVersion.ExecCommand.Execute() in C:\git\code\GitVersion\src\GitVersionExe\ExecCommand.cs:line 40
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) in C:\git\code\GitVersion\src\GitVersionExe\GitVersionExecutor.cs:line 117  INFO [01/07/20 20:31:24:18]   INFO [01/07/20 20:31:24:18] Attempting to show the current git graph (please include in issue):   INFO [01/07/20 20:31:24:18] Showing max of 100 commits  INFO [01/07/20 20:31:24:29] * 9bb62fb 52 minutes ago  (HEAD)
* 867dace 54 minutes ago  (origin/FeatureBranch, FeatureBranch)
* 9176cf2 56 minutes ago 
* b44da0d 58 minutes ago  (tag: 1.0.3, origin/master)
```

Such errors are completely ignored by Newtonsoft.Json.

**Comment by asbjornu** [comment]
How can such errors be ignored, @casz? `Newtonsoft.Json` will throw regular `Exception`s in the case of unparseable JSON, no?

**Comment by casz** [comment]
Still think this is mergable, I can cleanup the Newtonsoft.Json in tests in a follow up PR.

File: src/GitVersionCore/BuildServers/AppVeyor.cs (hunk 1 above)
Comment (asbjornu) [reply src/GitVersionCore/BuildServers/AppVeyor.cs]: Are you sure?

Comment (casz) [reply src/GitVersionCore/BuildServers/AppVeyor.cs]: Before it was going through JsonConvert.SerializeObject as object prior with the value of `value = $"{value}"` ergo it was turned into strings.

**Comment by asbjornu** [comment]
Hm. Is the serialization of integers related to #1688 in any way?

File: src/GitVersionCore/BuildServers/AppVeyor.cs (hunk 1 above)
Comment (asbjornu) [reply src/GitVersionCore/BuildServers/AppVeyor.cs]: Good point. Let's tackle that in a separate PR, if at all.

**Comment by asbjornu** [comment]
Thank you so much for your contributions, @casz! 🙏

**Comment by casz** [comment]
I believe the JSON Output formatter does not check for now null or empty.
I have #2019 I can fix it there, once I get back to it.

**Comment by asbjornu** [comment]
Sounds good, @casz.
