### PR TITLE
Fixes #2122 - sequence contains no elements when using IgnoreConfig

### LINKED ISSUE #2122: System.InvalidOperationException - ignore commits-before in GitVersion.yml
There are multiple folders in our repository with separate release cadence and different versions.

Adding a new folder, we would like it versioned starting from 0.0.0 hence we want it not to count the commits before the date it got added. The GitVersion.yml looks as below:

```
assembly-versioning-scheme: None
mode: Mainline
next-version: 0.0.0
branches: {}
ignore:
  commits-before: '2020-02-17T13:57:12'
increment: Inherit
commit-message-incrementing: MergeMessageOnly
```

Running gitversion.exe or dotnet-gitversion.exe in the folder throws an exception:
```
An unexpected error occurred:
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion(GitVersionContext context)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionFinder.FindVersion(GitVersionContext context)
   at GitVersion.GitVersionCalculator.<>c__DisplayClass14_0.<ExecuteInternal>b__0(IRepository repo)
   at GitVersion.Extensions.LibGitExtensions.WithRepository[TResult](String dotGitDirectory, Func`2 action)
   at GitVersion.GitVersionCalculator.ExecuteInternal(String targetBranch, String commitId, Config overrideConfig)
   at GitVersion.GitVersionCalculator.GetCachedGitVersionInfo(String targetBranch, String commitId, Config overrideConfig, Boolean noCache)
   at GitVersion.GitVersionCalculator.CalculateVersionVariables()
   at GitVersion.ExecCommand.Execute()
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments) 
```

It seems to works without the section below to get a version.
```
ignore:
  commits-before: '2020-02-17T13:57:12'
```
But it gets 2.0.235 or so which is not how we want the contents of that folder versioned.

**Versions tried with:**
gitversion /version
5.1.3+Branch.master.Sha.bef8ebc0b62b3ddd0cdafe09b66d68bbfcaf90d5
dotnet-gitversion.exe /version
5.1.3+Branch.master.Sha.bef8ebc0b62b3ddd0cdafe09b66d68bbfcaf90d5

Also tried with:
dotnet-gitversion.exe /version
5.1.4-beta.1+172.Branch.master.Sha.c602fbb304b8f39aecb39656f921c5898414283d

Are we doing something wrong?
Can anyone guide us please.

### PR DESCRIPTION
**Pull request by DamianKedzior**
When using IgnoreConfig and ignoring all commits to start from scratch (from 0.1.0) all version strategies were ignored, including Fallback one. This was causing sequence contains no elements exception. 

## Description
Change I made excludes VersionFilters for FallbackVersionStrategy.

## Related Issue
#2122 

## Motivation and Context
When forking existing repo which contains tags with version numbers and trying to start versioning from scratch you could specify `IgnoreConfig` to skip previous commits. Currently this is not possible because it throws exception.

## How Has This Been Tested?
There is new integration tests added for this scenario.

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/GitVersionCore/VersionCalculation/BaseVersionCalculator.cs [hunk 1]
```diff
@@ -28,23 +28,27 @@ public BaseVersion GetBaseVersion()
...
+                            .Where(v =>
                             {
-                                log.Info(reason);
-                                return false;
-                            }
-                        }
-
-                        return true;
+                                if (v == null) return false;
+                                if (s is FallbackVersionStrategy) return true;
```
Comment (asbjornu) [inline src/GitVersionCore/VersionCalculation/BaseVersionCalculator.cs:37]: Couldn't this this `if` statement be moved to the outer scope since it only concerns itself with the strategies `s` variable?

Comment (DamianKedzior) [reply src/GitVersionCore/VersionCalculation/BaseVersionCalculator.cs]: Good point, updated and pushed.

**Comment by asbjornu** [comment]
Thank you so much for your contribution, @DamianKedzior! 🙏

**Comment by DamianKedzior** [comment]
@asbjornu glad I could help!
