### PR TITLE
fix version cache key in msbuild task

### LINKED ISSUE #488: Version number is not cached between projects in a solution
As mentioned in #437, when GitVersionTask (version 3 beta 4) is installed in a solution, I get the following informational message when building every project in the solution.
```
INFO [07/08/15 14:57:03:21] Version not in cache. Calculating version.
```
It would speed the build up noticeably if the version number was successfully cached between projects.

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #488

### CODE REVIEW

File: src/GitVersionTask/VersionAndBranchFinder.cs [hunk 1]
```diff
@@ -27,17 +27,20 @@ public static VersionVariables GetVersion(string directory, Authentication authe
         var gitDir = GitDirFinder.TreeWalkForDotGitDir(directory);
         using (var repo = RepositoryLoader.GetRepo(gitDir))
         {
-            var ticks = DirectoryDateFinder.GetLastDirectoryWrite(directory);
-            var key = string.Format("{0}:{1}:{2}", repo.Head.CanonicalName, repo.Head.Tip.Sha, ticks);
+            var ticks = DirectoryDateFinder.GetLastDirectoryWrite(gitDir);
+            var key = string.Format("{0}:{1}:{2}",gitDir, repo.Head.CanonicalName, repo.Head.Tip.Sha);
```
Comment (JakeGinnivan) [inline src/GitVersionTask/VersionAndBranchFinder.cs]: Ticks is no longer used?

Comment (JakeGinnivan) [inline src/GitVersionTask/VersionAndBranchFinder.cs]: `var key = string.Format("{0}:{1}:{2}:{3}",gitDir, repo.Head.CanonicalName, repo.Head.Tip.Sha, ticks);` ?

Comment (SimonCropp) [inline src/GitVersionTask/VersionAndBranchFinder.cs]: we dont want ticks in the key. they are used in the second step. a static dictionary is bascially a memory leak. keying on ticks is not great since we gradually add more to the dictionary on every change.

Comment (JakeGinnivan) [inline src/GitVersionTask/VersionAndBranchFinder.cs]: Makes sense, if tip sha has changed, recalc. Got it

Comment (asbjornu) [inline src/GitVersionTask/VersionAndBranchFinder.cs]: The dictionary should probably be changed to a [`ConcurrentDictionary`](https://msdn.microsoft.com/en-us/library/dd287191.aspx) too, to avoid race conditions and concurrency issues if (and with Roslyn; when) the build is parallelized.

Comment (SimonCropp) [inline src/GitVersionTask/VersionAndBranchFinder.cs]: @asbjornu agreed. make it so
